package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.AlertExchange;
import wang.raye.springboot.model.AlertExchangeCriteria;

public interface AlertExchangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertExchangeSqlProvider.class, method="countByExample")
    long countByExample(AlertExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @DeleteProvider(type=AlertExchangeSqlProvider.class, method="deleteByExample")
    int deleteByExample(AlertExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @Delete({
        "delete from alert_exchange",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @Insert({
        "insert into alert_exchange (id, exchange, ",
        "base, openflg, url, ",
        "urlflg)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{base,jdbcType=VARCHAR}, #{openflg,jdbcType=CHAR}, #{url,jdbcType=VARCHAR}, ",
        "#{urlflg,jdbcType=CHAR})"
    })
    int insert(AlertExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @InsertProvider(type=AlertExchangeSqlProvider.class, method="insertSelective")
    int insertSelective(AlertExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @SelectProvider(type=AlertExchangeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="urlflg", property="urlflg", jdbcType=JdbcType.CHAR)
    })
    List<AlertExchange> selectByExample(AlertExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, base, openflg, url, urlflg",
        "from alert_exchange",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="openflg", property="openflg", jdbcType=JdbcType.CHAR),
        @Result(column="url", property="url", jdbcType=JdbcType.VARCHAR),
        @Result(column="urlflg", property="urlflg", jdbcType=JdbcType.CHAR)
    })
    AlertExchange selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertExchangeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") AlertExchange record, @Param("example") AlertExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertExchangeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") AlertExchange record, @Param("example") AlertExchangeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @UpdateProvider(type=AlertExchangeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(AlertExchange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    @Update({
        "update alert_exchange",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "base = #{base,jdbcType=VARCHAR},",
          "openflg = #{openflg,jdbcType=CHAR},",
          "url = #{url,jdbcType=VARCHAR},",
          "urlflg = #{urlflg,jdbcType=CHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(AlertExchange record);
}