package wang.raye.springboot.model.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import wang.raye.springboot.model.AlertExchange;
import wang.raye.springboot.model.AlertExchangeCriteria.Criteria;
import wang.raye.springboot.model.AlertExchangeCriteria.Criterion;
import wang.raye.springboot.model.AlertExchangeCriteria;

public class AlertExchangeSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String countByExample(AlertExchangeCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("alert_exchange");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String deleteByExample(AlertExchangeCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("alert_exchange");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String insertSelective(AlertExchange record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("alert_exchange");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getExchange() != null) {
            sql.VALUES("exchange", "#{exchange,jdbcType=VARCHAR}");
        }
        
        if (record.getBase() != null) {
            sql.VALUES("base", "#{base,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenflg() != null) {
            sql.VALUES("openflg", "#{openflg,jdbcType=CHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUrlflg() != null) {
            sql.VALUES("urlflg", "#{urlflg,jdbcType=CHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String selectByExample(AlertExchangeCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("exchange");
        sql.SELECT("base");
        sql.SELECT("openflg");
        sql.SELECT("url");
        sql.SELECT("urlflg");
        sql.FROM("alert_exchange");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        AlertExchange record = (AlertExchange) parameter.get("record");
        AlertExchangeCriteria example = (AlertExchangeCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("alert_exchange");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getExchange() != null) {
            sql.SET("exchange = #{record.exchange,jdbcType=VARCHAR}");
        }
        
        if (record.getBase() != null) {
            sql.SET("base = #{record.base,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenflg() != null) {
            sql.SET("openflg = #{record.openflg,jdbcType=CHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        }
        
        if (record.getUrlflg() != null) {
            sql.SET("urlflg = #{record.urlflg,jdbcType=CHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("alert_exchange");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("exchange = #{record.exchange,jdbcType=VARCHAR}");
        sql.SET("base = #{record.base,jdbcType=VARCHAR}");
        sql.SET("openflg = #{record.openflg,jdbcType=CHAR}");
        sql.SET("url = #{record.url,jdbcType=VARCHAR}");
        sql.SET("urlflg = #{record.urlflg,jdbcType=CHAR}");
        
        AlertExchangeCriteria example = (AlertExchangeCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(AlertExchange record) {
        SQL sql = new SQL();
        sql.UPDATE("alert_exchange");
        
        if (record.getExchange() != null) {
            sql.SET("exchange = #{exchange,jdbcType=VARCHAR}");
        }
        
        if (record.getBase() != null) {
            sql.SET("base = #{base,jdbcType=VARCHAR}");
        }
        
        if (record.getOpenflg() != null) {
            sql.SET("openflg = #{openflg,jdbcType=CHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUrlflg() != null) {
            sql.SET("urlflg = #{urlflg,jdbcType=CHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table alert_exchange
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, AlertExchangeCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}