package wang.raye.springboot.model.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import wang.raye.springboot.model.Pairs;
import wang.raye.springboot.model.PairsCriteria.Criteria;
import wang.raye.springboot.model.PairsCriteria.Criterion;
import wang.raye.springboot.model.PairsCriteria;

public class PairsSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String countByExample(PairsCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("pairs");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String deleteByExample(PairsCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("pairs");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String insertSelective(Pairs record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("pairs");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMarket() != null) {
            sql.VALUES("market", "#{market,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.VALUES("market_alias", "#{marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.VALUES("symbol", "#{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolAlias() != null) {
            sql.VALUES("symbol_alias", "#{symbolAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.VALUES("currency", "#{currency,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
        }
        
        if (record.getHasKilne() != null) {
            sql.VALUES("has_kilne", "#{hasKilne,jdbcType=CHAR}");
        }
        
        if (record.getListat() != null) {
            sql.VALUES("listAt", "#{listat,jdbcType=VARCHAR}");
        }
        
        if (record.getTradedat() != null) {
            sql.VALUES("tradedAt", "#{tradedat,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String selectByExample(PairsCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("market");
        sql.SELECT("market_alias");
        sql.SELECT("symbol");
        sql.SELECT("symbol_alias");
        sql.SELECT("currency");
        sql.SELECT("status");
        sql.SELECT("has_kilne");
        sql.SELECT("listAt");
        sql.SELECT("tradedAt");
        sql.FROM("pairs");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Pairs record = (Pairs) parameter.get("record");
        PairsCriteria example = (PairsCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("pairs");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getMarket() != null) {
            sql.SET("market = #{record.market,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.SET("market_alias = #{record.marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolAlias() != null) {
            sql.SET("symbol_alias = #{record.symbolAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.SET("currency = #{record.currency,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        }
        
        if (record.getHasKilne() != null) {
            sql.SET("has_kilne = #{record.hasKilne,jdbcType=CHAR}");
        }
        
        if (record.getListat() != null) {
            sql.SET("listAt = #{record.listat,jdbcType=VARCHAR}");
        }
        
        if (record.getTradedat() != null) {
            sql.SET("tradedAt = #{record.tradedat,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("pairs");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("market = #{record.market,jdbcType=VARCHAR}");
        sql.SET("market_alias = #{record.marketAlias,jdbcType=VARCHAR}");
        sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        sql.SET("symbol_alias = #{record.symbolAlias,jdbcType=VARCHAR}");
        sql.SET("currency = #{record.currency,jdbcType=VARCHAR}");
        sql.SET("status = #{record.status,jdbcType=VARCHAR}");
        sql.SET("has_kilne = #{record.hasKilne,jdbcType=CHAR}");
        sql.SET("listAt = #{record.listat,jdbcType=VARCHAR}");
        sql.SET("tradedAt = #{record.tradedat,jdbcType=VARCHAR}");
        
        PairsCriteria example = (PairsCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(Pairs record) {
        SQL sql = new SQL();
        sql.UPDATE("pairs");
        
        if (record.getMarket() != null) {
            sql.SET("market = #{market,jdbcType=VARCHAR}");
        }
        
        if (record.getMarketAlias() != null) {
            sql.SET("market_alias = #{marketAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolAlias() != null) {
            sql.SET("symbol_alias = #{symbolAlias,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.SET("currency = #{currency,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=VARCHAR}");
        }
        
        if (record.getHasKilne() != null) {
            sql.SET("has_kilne = #{hasKilne,jdbcType=CHAR}");
        }
        
        if (record.getListat() != null) {
            sql.SET("listAt = #{listat,jdbcType=VARCHAR}");
        }
        
        if (record.getTradedat() != null) {
            sql.SET("tradedAt = #{tradedat,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, PairsCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}