package wang.raye.springboot.model.mapper;

import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;
import wang.raye.springboot.model.PairsNew;
import wang.raye.springboot.model.PairsNewCriteria.Criteria;
import wang.raye.springboot.model.PairsNewCriteria.Criterion;
import wang.raye.springboot.model.PairsNewCriteria;

public class PairsNewSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String countByExample(PairsNewCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("pairs_new");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String deleteByExample(PairsNewCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("pairs_new");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String insertSelective(PairsNew record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("pairs_new");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getMarket() != null) {
            sql.VALUES("market", "#{market,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.VALUES("symbol", "#{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolId() != null) {
            sql.VALUES("symbol_id", "#{symbolId,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.VALUES("currency", "#{currency,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinInfo() != null) {
            sql.VALUES("coin_info", "#{coinInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinUrl() != null) {
            sql.VALUES("coin_url", "#{coinUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAt() != null) {
            sql.VALUES("charge_at", "#{chargeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getWithdrawAt() != null) {
            sql.VALUES("withdraw_at", "#{withdrawAt,jdbcType=VARCHAR}");
        }
        
        if (record.getEndAt() != null) {
            sql.VALUES("end_at", "#{endAt,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeAt() != null) {
            sql.VALUES("trade_at", "#{tradeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.VALUES("price", "#{price,jdbcType=VARCHAR}");
        }
        
        if (record.getChange1d() != null) {
            sql.VALUES("change1d", "#{change1d,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String selectByExample(PairsNewCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("market");
        sql.SELECT("symbol");
        sql.SELECT("symbol_id");
        sql.SELECT("currency");
        sql.SELECT("coin_info");
        sql.SELECT("coin_url");
        sql.SELECT("charge_at");
        sql.SELECT("withdraw_at");
        sql.SELECT("end_at");
        sql.SELECT("trade_at");
        sql.SELECT("price");
        sql.SELECT("change1d");
        sql.FROM("pairs_new");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        PairsNew record = (PairsNew) parameter.get("record");
        PairsNewCriteria example = (PairsNewCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("pairs_new");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getMarket() != null) {
            sql.SET("market = #{record.market,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolId() != null) {
            sql.SET("symbol_id = #{record.symbolId,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.SET("currency = #{record.currency,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinInfo() != null) {
            sql.SET("coin_info = #{record.coinInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinUrl() != null) {
            sql.SET("coin_url = #{record.coinUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAt() != null) {
            sql.SET("charge_at = #{record.chargeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getWithdrawAt() != null) {
            sql.SET("withdraw_at = #{record.withdrawAt,jdbcType=VARCHAR}");
        }
        
        if (record.getEndAt() != null) {
            sql.SET("end_at = #{record.endAt,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeAt() != null) {
            sql.SET("trade_at = #{record.tradeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        }
        
        if (record.getChange1d() != null) {
            sql.SET("change1d = #{record.change1d,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("pairs_new");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("market = #{record.market,jdbcType=VARCHAR}");
        sql.SET("symbol = #{record.symbol,jdbcType=VARCHAR}");
        sql.SET("symbol_id = #{record.symbolId,jdbcType=VARCHAR}");
        sql.SET("currency = #{record.currency,jdbcType=VARCHAR}");
        sql.SET("coin_info = #{record.coinInfo,jdbcType=VARCHAR}");
        sql.SET("coin_url = #{record.coinUrl,jdbcType=VARCHAR}");
        sql.SET("charge_at = #{record.chargeAt,jdbcType=VARCHAR}");
        sql.SET("withdraw_at = #{record.withdrawAt,jdbcType=VARCHAR}");
        sql.SET("end_at = #{record.endAt,jdbcType=VARCHAR}");
        sql.SET("trade_at = #{record.tradeAt,jdbcType=VARCHAR}");
        sql.SET("price = #{record.price,jdbcType=VARCHAR}");
        sql.SET("change1d = #{record.change1d,jdbcType=VARCHAR}");
        
        PairsNewCriteria example = (PairsNewCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(PairsNew record) {
        SQL sql = new SQL();
        sql.UPDATE("pairs_new");
        
        if (record.getMarket() != null) {
            sql.SET("market = #{market,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbol() != null) {
            sql.SET("symbol = #{symbol,jdbcType=VARCHAR}");
        }
        
        if (record.getSymbolId() != null) {
            sql.SET("symbol_id = #{symbolId,jdbcType=VARCHAR}");
        }
        
        if (record.getCurrency() != null) {
            sql.SET("currency = #{currency,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinInfo() != null) {
            sql.SET("coin_info = #{coinInfo,jdbcType=VARCHAR}");
        }
        
        if (record.getCoinUrl() != null) {
            sql.SET("coin_url = #{coinUrl,jdbcType=VARCHAR}");
        }
        
        if (record.getChargeAt() != null) {
            sql.SET("charge_at = #{chargeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getWithdrawAt() != null) {
            sql.SET("withdraw_at = #{withdrawAt,jdbcType=VARCHAR}");
        }
        
        if (record.getEndAt() != null) {
            sql.SET("end_at = #{endAt,jdbcType=VARCHAR}");
        }
        
        if (record.getTradeAt() != null) {
            sql.SET("trade_at = #{tradeAt,jdbcType=VARCHAR}");
        }
        
        if (record.getPrice() != null) {
            sql.SET("price = #{price,jdbcType=VARCHAR}");
        }
        
        if (record.getChange1d() != null) {
            sql.SET("change1d = #{change1d,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pairs_new
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, PairsNewCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}