package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.TradePointQuota;
import wang.raye.springboot.model.TradePointQuotaCriteria;

public interface TradePointQuotaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @SelectProvider(type=TradePointQuotaSqlProvider.class, method="countByExample")
    long countByExample(TradePointQuotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TradePointQuotaSqlProvider.class, method="deleteByExample")
    int deleteByExample(TradePointQuotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @Delete({
        "delete from trade_point_quota",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @Insert({
        "insert into trade_point_quota (id, exchange, ",
        "symbol, base, period, ",
        "quant_type, quota_type, ",
        "quota1, quota2, quota3, ",
        "quota4, quota5, price, ",
        "status, kline_time, ",
        "time)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{symbol,jdbcType=VARCHAR}, #{base,jdbcType=VARCHAR}, #{period,jdbcType=VARCHAR}, ",
        "#{quantType,jdbcType=VARCHAR}, #{quotaType,jdbcType=VARCHAR}, ",
        "#{quota1,jdbcType=DOUBLE}, #{quota2,jdbcType=DOUBLE}, #{quota3,jdbcType=DOUBLE}, ",
        "#{quota4,jdbcType=DOUBLE}, #{quota5,jdbcType=DOUBLE}, #{price,jdbcType=DOUBLE}, ",
        "#{status,jdbcType=CHAR}, #{klineTime,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=TIMESTAMP})"
    })
    int insert(TradePointQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @InsertProvider(type=TradePointQuotaSqlProvider.class, method="insertSelective")
    int insertSelective(TradePointQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @SelectProvider(type=TradePointQuotaSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="quant_type", property="quantType", jdbcType=JdbcType.VARCHAR),
        @Result(column="quota_type", property="quotaType", jdbcType=JdbcType.VARCHAR),
        @Result(column="quota1", property="quota1", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota2", property="quota2", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota3", property="quota3", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota4", property="quota4", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota5", property="quota5", jdbcType=JdbcType.DOUBLE),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="kline_time", property="klineTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TradePointQuota> selectByExample(TradePointQuotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, symbol, base, period, quant_type, quota_type, quota1, quota2, ",
        "quota3, quota4, quota5, price, status, kline_time, time",
        "from trade_point_quota",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="quant_type", property="quantType", jdbcType=JdbcType.VARCHAR),
        @Result(column="quota_type", property="quotaType", jdbcType=JdbcType.VARCHAR),
        @Result(column="quota1", property="quota1", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota2", property="quota2", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota3", property="quota3", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota4", property="quota4", jdbcType=JdbcType.DOUBLE),
        @Result(column="quota5", property="quota5", jdbcType=JdbcType.DOUBLE),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="kline_time", property="klineTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    TradePointQuota selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointQuotaSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TradePointQuota record, @Param("example") TradePointQuotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointQuotaSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TradePointQuota record, @Param("example") TradePointQuotaCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointQuotaSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TradePointQuota record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_quota
     *
     * @mbg.generated
     */
    @Update({
        "update trade_point_quota",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "symbol = #{symbol,jdbcType=VARCHAR},",
          "base = #{base,jdbcType=VARCHAR},",
          "period = #{period,jdbcType=VARCHAR},",
          "quant_type = #{quantType,jdbcType=VARCHAR},",
          "quota_type = #{quotaType,jdbcType=VARCHAR},",
          "quota1 = #{quota1,jdbcType=DOUBLE},",
          "quota2 = #{quota2,jdbcType=DOUBLE},",
          "quota3 = #{quota3,jdbcType=DOUBLE},",
          "quota4 = #{quota4,jdbcType=DOUBLE},",
          "quota5 = #{quota5,jdbcType=DOUBLE},",
          "price = #{price,jdbcType=DOUBLE},",
          "status = #{status,jdbcType=CHAR},",
          "kline_time = #{klineTime,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TradePointQuota record);
}