package wang.raye.springboot.model.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import wang.raye.springboot.model.TradePointExclude;
import wang.raye.springboot.model.TradePointExcludeCriteria;

public interface TradePointExcludeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @SelectProvider(type=TradePointExcludeSqlProvider.class, method="countByExample")
    long countByExample(TradePointExcludeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @DeleteProvider(type=TradePointExcludeSqlProvider.class, method="deleteByExample")
    int deleteByExample(TradePointExcludeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @Delete({
        "delete from trade_point_exclude",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @Insert({
        "insert into trade_point_exclude (id, exchange, ",
        "symbol, base, period, ",
        "price, status, kline_time, ",
        "time)",
        "values (#{id,jdbcType=INTEGER}, #{exchange,jdbcType=VARCHAR}, ",
        "#{symbol,jdbcType=VARCHAR}, #{base,jdbcType=VARCHAR}, #{period,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DOUBLE}, #{status,jdbcType=CHAR}, #{klineTime,jdbcType=VARCHAR}, ",
        "#{time,jdbcType=TIMESTAMP})"
    })
    int insert(TradePointExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @InsertProvider(type=TradePointExcludeSqlProvider.class, method="insertSelective")
    int insertSelective(TradePointExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @SelectProvider(type=TradePointExcludeSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="kline_time", property="klineTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    List<TradePointExclude> selectByExample(TradePointExcludeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, exchange, symbol, base, period, price, status, kline_time, time",
        "from trade_point_exclude",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="exchange", property="exchange", jdbcType=JdbcType.VARCHAR),
        @Result(column="symbol", property="symbol", jdbcType=JdbcType.VARCHAR),
        @Result(column="base", property="base", jdbcType=JdbcType.VARCHAR),
        @Result(column="period", property="period", jdbcType=JdbcType.VARCHAR),
        @Result(column="price", property="price", jdbcType=JdbcType.DOUBLE),
        @Result(column="status", property="status", jdbcType=JdbcType.CHAR),
        @Result(column="kline_time", property="klineTime", jdbcType=JdbcType.VARCHAR),
        @Result(column="time", property="time", jdbcType=JdbcType.TIMESTAMP)
    })
    TradePointExclude selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointExcludeSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") TradePointExclude record, @Param("example") TradePointExcludeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointExcludeSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") TradePointExclude record, @Param("example") TradePointExcludeCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @UpdateProvider(type=TradePointExcludeSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(TradePointExclude record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_point_exclude
     *
     * @mbg.generated
     */
    @Update({
        "update trade_point_exclude",
        "set exchange = #{exchange,jdbcType=VARCHAR},",
          "symbol = #{symbol,jdbcType=VARCHAR},",
          "base = #{base,jdbcType=VARCHAR},",
          "period = #{period,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DOUBLE},",
          "status = #{status,jdbcType=CHAR},",
          "kline_time = #{klineTime,jdbcType=VARCHAR},",
          "time = #{time,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(TradePointExclude record);
}