package wang.raye.springboot.model;

public class AlertExchange {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.base
     *
     * @mbg.generated
     */
    private String base;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.openflg
     *
     * @mbg.generated
     */
    private String openflg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column alert_exchange.urlflg
     *
     * @mbg.generated
     */
    private String urlflg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.id
     *
     * @return the value of alert_exchange.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.id
     *
     * @param id the value for alert_exchange.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.exchange
     *
     * @return the value of alert_exchange.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.exchange
     *
     * @param exchange the value for alert_exchange.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.base
     *
     * @return the value of alert_exchange.base
     *
     * @mbg.generated
     */
    public String getBase() {
        return base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.base
     *
     * @param base the value for alert_exchange.base
     *
     * @mbg.generated
     */
    public void setBase(String base) {
        this.base = base == null ? null : base.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.openflg
     *
     * @return the value of alert_exchange.openflg
     *
     * @mbg.generated
     */
    public String getOpenflg() {
        return openflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.openflg
     *
     * @param openflg the value for alert_exchange.openflg
     *
     * @mbg.generated
     */
    public void setOpenflg(String openflg) {
        this.openflg = openflg == null ? null : openflg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.url
     *
     * @return the value of alert_exchange.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.url
     *
     * @param url the value for alert_exchange.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column alert_exchange.urlflg
     *
     * @return the value of alert_exchange.urlflg
     *
     * @mbg.generated
     */
    public String getUrlflg() {
        return urlflg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column alert_exchange.urlflg
     *
     * @param urlflg the value for alert_exchange.urlflg
     *
     * @mbg.generated
     */
    public void setUrlflg(String urlflg) {
        this.urlflg = urlflg == null ? null : urlflg.trim();
    }
}