package wang.raye.springboot.model;

import java.util.Date;

public class MacdCross {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota1
     *
     * @mbg.generated
     */
    private Double quota1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota2
     *
     * @mbg.generated
     */
    private Double quota2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota3
     *
     * @mbg.generated
     */
    private Double quota3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.quota4
     *
     * @mbg.generated
     */
    private Double quota4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.pre_quota1
     *
     * @mbg.generated
     */
    private Double preQuota1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.pre_quota2
     *
     * @mbg.generated
     */
    private Double preQuota2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.pre_quota3
     *
     * @mbg.generated
     */
    private Double preQuota3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.pre_quota4
     *
     * @mbg.generated
     */
    private Double preQuota4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.thr_quota1
     *
     * @mbg.generated
     */
    private Double thrQuota1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.thr_quota2
     *
     * @mbg.generated
     */
    private Double thrQuota2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.thr_quota3
     *
     * @mbg.generated
     */
    private Double thrQuota3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.thr_quota4
     *
     * @mbg.generated
     */
    private Double thrQuota4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.pre_price
     *
     * @mbg.generated
     */
    private Double prePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.thr_price
     *
     * @mbg.generated
     */
    private Double thrPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.min_low
     *
     * @mbg.generated
     */
    private Double minLow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.max_high
     *
     * @mbg.generated
     */
    private Double maxHigh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.kline_time
     *
     * @mbg.generated
     */
    private String klineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column macd_cross.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.id
     *
     * @return the value of macd_cross.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.id
     *
     * @param id the value for macd_cross.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.exchange
     *
     * @return the value of macd_cross.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.exchange
     *
     * @param exchange the value for macd_cross.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.symbol
     *
     * @return the value of macd_cross.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.symbol
     *
     * @param symbol the value for macd_cross.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.type
     *
     * @return the value of macd_cross.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.type
     *
     * @param type the value for macd_cross.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.status
     *
     * @return the value of macd_cross.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.status
     *
     * @param status the value for macd_cross.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota1
     *
     * @return the value of macd_cross.quota1
     *
     * @mbg.generated
     */
    public Double getQuota1() {
        return quota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota1
     *
     * @param quota1 the value for macd_cross.quota1
     *
     * @mbg.generated
     */
    public void setQuota1(Double quota1) {
        this.quota1 = quota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota2
     *
     * @return the value of macd_cross.quota2
     *
     * @mbg.generated
     */
    public Double getQuota2() {
        return quota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota2
     *
     * @param quota2 the value for macd_cross.quota2
     *
     * @mbg.generated
     */
    public void setQuota2(Double quota2) {
        this.quota2 = quota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota3
     *
     * @return the value of macd_cross.quota3
     *
     * @mbg.generated
     */
    public Double getQuota3() {
        return quota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota3
     *
     * @param quota3 the value for macd_cross.quota3
     *
     * @mbg.generated
     */
    public void setQuota3(Double quota3) {
        this.quota3 = quota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.quota4
     *
     * @return the value of macd_cross.quota4
     *
     * @mbg.generated
     */
    public Double getQuota4() {
        return quota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.quota4
     *
     * @param quota4 the value for macd_cross.quota4
     *
     * @mbg.generated
     */
    public void setQuota4(Double quota4) {
        this.quota4 = quota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.pre_quota1
     *
     * @return the value of macd_cross.pre_quota1
     *
     * @mbg.generated
     */
    public Double getPreQuota1() {
        return preQuota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.pre_quota1
     *
     * @param preQuota1 the value for macd_cross.pre_quota1
     *
     * @mbg.generated
     */
    public void setPreQuota1(Double preQuota1) {
        this.preQuota1 = preQuota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.pre_quota2
     *
     * @return the value of macd_cross.pre_quota2
     *
     * @mbg.generated
     */
    public Double getPreQuota2() {
        return preQuota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.pre_quota2
     *
     * @param preQuota2 the value for macd_cross.pre_quota2
     *
     * @mbg.generated
     */
    public void setPreQuota2(Double preQuota2) {
        this.preQuota2 = preQuota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.pre_quota3
     *
     * @return the value of macd_cross.pre_quota3
     *
     * @mbg.generated
     */
    public Double getPreQuota3() {
        return preQuota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.pre_quota3
     *
     * @param preQuota3 the value for macd_cross.pre_quota3
     *
     * @mbg.generated
     */
    public void setPreQuota3(Double preQuota3) {
        this.preQuota3 = preQuota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.pre_quota4
     *
     * @return the value of macd_cross.pre_quota4
     *
     * @mbg.generated
     */
    public Double getPreQuota4() {
        return preQuota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.pre_quota4
     *
     * @param preQuota4 the value for macd_cross.pre_quota4
     *
     * @mbg.generated
     */
    public void setPreQuota4(Double preQuota4) {
        this.preQuota4 = preQuota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.thr_quota1
     *
     * @return the value of macd_cross.thr_quota1
     *
     * @mbg.generated
     */
    public Double getThrQuota1() {
        return thrQuota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.thr_quota1
     *
     * @param thrQuota1 the value for macd_cross.thr_quota1
     *
     * @mbg.generated
     */
    public void setThrQuota1(Double thrQuota1) {
        this.thrQuota1 = thrQuota1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.thr_quota2
     *
     * @return the value of macd_cross.thr_quota2
     *
     * @mbg.generated
     */
    public Double getThrQuota2() {
        return thrQuota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.thr_quota2
     *
     * @param thrQuota2 the value for macd_cross.thr_quota2
     *
     * @mbg.generated
     */
    public void setThrQuota2(Double thrQuota2) {
        this.thrQuota2 = thrQuota2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.thr_quota3
     *
     * @return the value of macd_cross.thr_quota3
     *
     * @mbg.generated
     */
    public Double getThrQuota3() {
        return thrQuota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.thr_quota3
     *
     * @param thrQuota3 the value for macd_cross.thr_quota3
     *
     * @mbg.generated
     */
    public void setThrQuota3(Double thrQuota3) {
        this.thrQuota3 = thrQuota3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.thr_quota4
     *
     * @return the value of macd_cross.thr_quota4
     *
     * @mbg.generated
     */
    public Double getThrQuota4() {
        return thrQuota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.thr_quota4
     *
     * @param thrQuota4 the value for macd_cross.thr_quota4
     *
     * @mbg.generated
     */
    public void setThrQuota4(Double thrQuota4) {
        this.thrQuota4 = thrQuota4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.price
     *
     * @return the value of macd_cross.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.price
     *
     * @param price the value for macd_cross.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.pre_price
     *
     * @return the value of macd_cross.pre_price
     *
     * @mbg.generated
     */
    public Double getPrePrice() {
        return prePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.pre_price
     *
     * @param prePrice the value for macd_cross.pre_price
     *
     * @mbg.generated
     */
    public void setPrePrice(Double prePrice) {
        this.prePrice = prePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.thr_price
     *
     * @return the value of macd_cross.thr_price
     *
     * @mbg.generated
     */
    public Double getThrPrice() {
        return thrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.thr_price
     *
     * @param thrPrice the value for macd_cross.thr_price
     *
     * @mbg.generated
     */
    public void setThrPrice(Double thrPrice) {
        this.thrPrice = thrPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.min_low
     *
     * @return the value of macd_cross.min_low
     *
     * @mbg.generated
     */
    public Double getMinLow() {
        return minLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.min_low
     *
     * @param minLow the value for macd_cross.min_low
     *
     * @mbg.generated
     */
    public void setMinLow(Double minLow) {
        this.minLow = minLow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.max_high
     *
     * @return the value of macd_cross.max_high
     *
     * @mbg.generated
     */
    public Double getMaxHigh() {
        return maxHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.max_high
     *
     * @param maxHigh the value for macd_cross.max_high
     *
     * @mbg.generated
     */
    public void setMaxHigh(Double maxHigh) {
        this.maxHigh = maxHigh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.period
     *
     * @return the value of macd_cross.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.period
     *
     * @param period the value for macd_cross.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.kline_time
     *
     * @return the value of macd_cross.kline_time
     *
     * @mbg.generated
     */
    public String getKlineTime() {
        return klineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.kline_time
     *
     * @param klineTime the value for macd_cross.kline_time
     *
     * @mbg.generated
     */
    public void setKlineTime(String klineTime) {
        this.klineTime = klineTime == null ? null : klineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column macd_cross.update_time
     *
     * @return the value of macd_cross.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column macd_cross.update_time
     *
     * @param updateTime the value for macd_cross.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}