package wang.raye.springboot.model;

public class Pairs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.market
     *
     * @mbg.generated
     */
    private String market;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.market_alias
     *
     * @mbg.generated
     */
    private String marketAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.symbol_alias
     *
     * @mbg.generated
     */
    private String symbolAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.currency
     *
     * @mbg.generated
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.has_kilne
     *
     * @mbg.generated
     */
    private String hasKilne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.listAt
     *
     * @mbg.generated
     */
    private String listat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pairs.tradedAt
     *
     * @mbg.generated
     */
    private String tradedat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.id
     *
     * @return the value of pairs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.id
     *
     * @param id the value for pairs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.market
     *
     * @return the value of pairs.market
     *
     * @mbg.generated
     */
    public String getMarket() {
        return market;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.market
     *
     * @param market the value for pairs.market
     *
     * @mbg.generated
     */
    public void setMarket(String market) {
        this.market = market == null ? null : market.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.market_alias
     *
     * @return the value of pairs.market_alias
     *
     * @mbg.generated
     */
    public String getMarketAlias() {
        return marketAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.market_alias
     *
     * @param marketAlias the value for pairs.market_alias
     *
     * @mbg.generated
     */
    public void setMarketAlias(String marketAlias) {
        this.marketAlias = marketAlias == null ? null : marketAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.symbol
     *
     * @return the value of pairs.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.symbol
     *
     * @param symbol the value for pairs.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.symbol_alias
     *
     * @return the value of pairs.symbol_alias
     *
     * @mbg.generated
     */
    public String getSymbolAlias() {
        return symbolAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.symbol_alias
     *
     * @param symbolAlias the value for pairs.symbol_alias
     *
     * @mbg.generated
     */
    public void setSymbolAlias(String symbolAlias) {
        this.symbolAlias = symbolAlias == null ? null : symbolAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.currency
     *
     * @return the value of pairs.currency
     *
     * @mbg.generated
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.currency
     *
     * @param currency the value for pairs.currency
     *
     * @mbg.generated
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.status
     *
     * @return the value of pairs.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.status
     *
     * @param status the value for pairs.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.has_kilne
     *
     * @return the value of pairs.has_kilne
     *
     * @mbg.generated
     */
    public String getHasKilne() {
        return hasKilne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.has_kilne
     *
     * @param hasKilne the value for pairs.has_kilne
     *
     * @mbg.generated
     */
    public void setHasKilne(String hasKilne) {
        this.hasKilne = hasKilne == null ? null : hasKilne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.listAt
     *
     * @return the value of pairs.listAt
     *
     * @mbg.generated
     */
    public String getListat() {
        return listat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.listAt
     *
     * @param listat the value for pairs.listAt
     *
     * @mbg.generated
     */
    public void setListat(String listat) {
        this.listat = listat == null ? null : listat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pairs.tradedAt
     *
     * @return the value of pairs.tradedAt
     *
     * @mbg.generated
     */
    public String getTradedat() {
        return tradedat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pairs.tradedAt
     *
     * @param tradedat the value for pairs.tradedAt
     *
     * @mbg.generated
     */
    public void setTradedat(String tradedat) {
        this.tradedat = tradedat == null ? null : tradedat.trim();
    }
}