package wang.raye.springboot.model;

public class Tickers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.ticker_id
     *
     * @mbg.generated
     */
    private String tickerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.display_pair_name
     *
     * @mbg.generated
     */
    private String displayPairName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.coin_symbol
     *
     * @mbg.generated
     */
    private String coinSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.coin_name
     *
     * @mbg.generated
     */
    private String coinName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.coin_id
     *
     * @mbg.generated
     */
    private String coinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.base_symbol
     *
     * @mbg.generated
     */
    private String baseSymbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.change1d
     *
     * @mbg.generated
     */
    private Double change1d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.bid
     *
     * @mbg.generated
     */
    private Double bid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.ask
     *
     * @mbg.generated
     */
    private Double ask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.native_price
     *
     * @mbg.generated
     */
    private Double nativePrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.low1d
     *
     * @mbg.generated
     */
    private Double low1d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.high1d
     *
     * @mbg.generated
     */
    private Double high1d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.exchange_display_name
     *
     * @mbg.generated
     */
    private String exchangeDisplayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.exchange_zh_name
     *
     * @mbg.generated
     */
    private String exchangeZhName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.exchange_name
     *
     * @mbg.generated
     */
    private String exchangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.dataCenter_pair_name
     *
     * @mbg.generated
     */
    private String datacenterPairName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.timestamps
     *
     * @mbg.generated
     */
    private String timestamps;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.enableKline
     *
     * @mbg.generated
     */
    private String enablekline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.volume
     *
     * @mbg.generated
     */
    private Double volume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.percent
     *
     * @mbg.generated
     */
    private Double percent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.base_volume
     *
     * @mbg.generated
     */
    private Double baseVolume;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.total_supply
     *
     * @mbg.generated
     */
    private Double totalSupply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.decimals
     *
     * @mbg.generated
     */
    private Integer decimals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.contract_address
     *
     * @mbg.generated
     */
    private String contractAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.contract_address_list
     *
     * @mbg.generated
     */
    private String contractAddressList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.marketcap
     *
     * @mbg.generated
     */
    private Double marketcap;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.change24h
     *
     * @mbg.generated
     */
    private Double change24h;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.change7d
     *
     * @mbg.generated
     */
    private Double change7d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tickers.rank
     *
     * @mbg.generated
     */
    private String rank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.id
     *
     * @return the value of tickers.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.id
     *
     * @param id the value for tickers.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.ticker_id
     *
     * @return the value of tickers.ticker_id
     *
     * @mbg.generated
     */
    public String getTickerId() {
        return tickerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.ticker_id
     *
     * @param tickerId the value for tickers.ticker_id
     *
     * @mbg.generated
     */
    public void setTickerId(String tickerId) {
        this.tickerId = tickerId == null ? null : tickerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.display_pair_name
     *
     * @return the value of tickers.display_pair_name
     *
     * @mbg.generated
     */
    public String getDisplayPairName() {
        return displayPairName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.display_pair_name
     *
     * @param displayPairName the value for tickers.display_pair_name
     *
     * @mbg.generated
     */
    public void setDisplayPairName(String displayPairName) {
        this.displayPairName = displayPairName == null ? null : displayPairName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.coin_symbol
     *
     * @return the value of tickers.coin_symbol
     *
     * @mbg.generated
     */
    public String getCoinSymbol() {
        return coinSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.coin_symbol
     *
     * @param coinSymbol the value for tickers.coin_symbol
     *
     * @mbg.generated
     */
    public void setCoinSymbol(String coinSymbol) {
        this.coinSymbol = coinSymbol == null ? null : coinSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.coin_name
     *
     * @return the value of tickers.coin_name
     *
     * @mbg.generated
     */
    public String getCoinName() {
        return coinName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.coin_name
     *
     * @param coinName the value for tickers.coin_name
     *
     * @mbg.generated
     */
    public void setCoinName(String coinName) {
        this.coinName = coinName == null ? null : coinName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.coin_id
     *
     * @return the value of tickers.coin_id
     *
     * @mbg.generated
     */
    public String getCoinId() {
        return coinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.coin_id
     *
     * @param coinId the value for tickers.coin_id
     *
     * @mbg.generated
     */
    public void setCoinId(String coinId) {
        this.coinId = coinId == null ? null : coinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.base_symbol
     *
     * @return the value of tickers.base_symbol
     *
     * @mbg.generated
     */
    public String getBaseSymbol() {
        return baseSymbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.base_symbol
     *
     * @param baseSymbol the value for tickers.base_symbol
     *
     * @mbg.generated
     */
    public void setBaseSymbol(String baseSymbol) {
        this.baseSymbol = baseSymbol == null ? null : baseSymbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.change1d
     *
     * @return the value of tickers.change1d
     *
     * @mbg.generated
     */
    public Double getChange1d() {
        return change1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.change1d
     *
     * @param change1d the value for tickers.change1d
     *
     * @mbg.generated
     */
    public void setChange1d(Double change1d) {
        this.change1d = change1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.type
     *
     * @return the value of tickers.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.type
     *
     * @param type the value for tickers.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.bid
     *
     * @return the value of tickers.bid
     *
     * @mbg.generated
     */
    public Double getBid() {
        return bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.bid
     *
     * @param bid the value for tickers.bid
     *
     * @mbg.generated
     */
    public void setBid(Double bid) {
        this.bid = bid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.ask
     *
     * @return the value of tickers.ask
     *
     * @mbg.generated
     */
    public Double getAsk() {
        return ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.ask
     *
     * @param ask the value for tickers.ask
     *
     * @mbg.generated
     */
    public void setAsk(Double ask) {
        this.ask = ask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.native_price
     *
     * @return the value of tickers.native_price
     *
     * @mbg.generated
     */
    public Double getNativePrice() {
        return nativePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.native_price
     *
     * @param nativePrice the value for tickers.native_price
     *
     * @mbg.generated
     */
    public void setNativePrice(Double nativePrice) {
        this.nativePrice = nativePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.low1d
     *
     * @return the value of tickers.low1d
     *
     * @mbg.generated
     */
    public Double getLow1d() {
        return low1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.low1d
     *
     * @param low1d the value for tickers.low1d
     *
     * @mbg.generated
     */
    public void setLow1d(Double low1d) {
        this.low1d = low1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.high1d
     *
     * @return the value of tickers.high1d
     *
     * @mbg.generated
     */
    public Double getHigh1d() {
        return high1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.high1d
     *
     * @param high1d the value for tickers.high1d
     *
     * @mbg.generated
     */
    public void setHigh1d(Double high1d) {
        this.high1d = high1d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.status
     *
     * @return the value of tickers.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.status
     *
     * @param status the value for tickers.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.exchange_display_name
     *
     * @return the value of tickers.exchange_display_name
     *
     * @mbg.generated
     */
    public String getExchangeDisplayName() {
        return exchangeDisplayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.exchange_display_name
     *
     * @param exchangeDisplayName the value for tickers.exchange_display_name
     *
     * @mbg.generated
     */
    public void setExchangeDisplayName(String exchangeDisplayName) {
        this.exchangeDisplayName = exchangeDisplayName == null ? null : exchangeDisplayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.exchange_zh_name
     *
     * @return the value of tickers.exchange_zh_name
     *
     * @mbg.generated
     */
    public String getExchangeZhName() {
        return exchangeZhName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.exchange_zh_name
     *
     * @param exchangeZhName the value for tickers.exchange_zh_name
     *
     * @mbg.generated
     */
    public void setExchangeZhName(String exchangeZhName) {
        this.exchangeZhName = exchangeZhName == null ? null : exchangeZhName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.exchange_name
     *
     * @return the value of tickers.exchange_name
     *
     * @mbg.generated
     */
    public String getExchangeName() {
        return exchangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.exchange_name
     *
     * @param exchangeName the value for tickers.exchange_name
     *
     * @mbg.generated
     */
    public void setExchangeName(String exchangeName) {
        this.exchangeName = exchangeName == null ? null : exchangeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.url
     *
     * @return the value of tickers.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.url
     *
     * @param url the value for tickers.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.dataCenter_pair_name
     *
     * @return the value of tickers.dataCenter_pair_name
     *
     * @mbg.generated
     */
    public String getDatacenterPairName() {
        return datacenterPairName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.dataCenter_pair_name
     *
     * @param datacenterPairName the value for tickers.dataCenter_pair_name
     *
     * @mbg.generated
     */
    public void setDatacenterPairName(String datacenterPairName) {
        this.datacenterPairName = datacenterPairName == null ? null : datacenterPairName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.timestamps
     *
     * @return the value of tickers.timestamps
     *
     * @mbg.generated
     */
    public String getTimestamps() {
        return timestamps;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.timestamps
     *
     * @param timestamps the value for tickers.timestamps
     *
     * @mbg.generated
     */
    public void setTimestamps(String timestamps) {
        this.timestamps = timestamps == null ? null : timestamps.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.enableKline
     *
     * @return the value of tickers.enableKline
     *
     * @mbg.generated
     */
    public String getEnablekline() {
        return enablekline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.enableKline
     *
     * @param enablekline the value for tickers.enableKline
     *
     * @mbg.generated
     */
    public void setEnablekline(String enablekline) {
        this.enablekline = enablekline == null ? null : enablekline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.period
     *
     * @return the value of tickers.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.period
     *
     * @param period the value for tickers.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.volume
     *
     * @return the value of tickers.volume
     *
     * @mbg.generated
     */
    public Double getVolume() {
        return volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.volume
     *
     * @param volume the value for tickers.volume
     *
     * @mbg.generated
     */
    public void setVolume(Double volume) {
        this.volume = volume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.price
     *
     * @return the value of tickers.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.price
     *
     * @param price the value for tickers.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.percent
     *
     * @return the value of tickers.percent
     *
     * @mbg.generated
     */
    public Double getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.percent
     *
     * @param percent the value for tickers.percent
     *
     * @mbg.generated
     */
    public void setPercent(Double percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.base_volume
     *
     * @return the value of tickers.base_volume
     *
     * @mbg.generated
     */
    public Double getBaseVolume() {
        return baseVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.base_volume
     *
     * @param baseVolume the value for tickers.base_volume
     *
     * @mbg.generated
     */
    public void setBaseVolume(Double baseVolume) {
        this.baseVolume = baseVolume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.total_supply
     *
     * @return the value of tickers.total_supply
     *
     * @mbg.generated
     */
    public Double getTotalSupply() {
        return totalSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.total_supply
     *
     * @param totalSupply the value for tickers.total_supply
     *
     * @mbg.generated
     */
    public void setTotalSupply(Double totalSupply) {
        this.totalSupply = totalSupply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.decimals
     *
     * @return the value of tickers.decimals
     *
     * @mbg.generated
     */
    public Integer getDecimals() {
        return decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.decimals
     *
     * @param decimals the value for tickers.decimals
     *
     * @mbg.generated
     */
    public void setDecimals(Integer decimals) {
        this.decimals = decimals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.contract_address
     *
     * @return the value of tickers.contract_address
     *
     * @mbg.generated
     */
    public String getContractAddress() {
        return contractAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.contract_address
     *
     * @param contractAddress the value for tickers.contract_address
     *
     * @mbg.generated
     */
    public void setContractAddress(String contractAddress) {
        this.contractAddress = contractAddress == null ? null : contractAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.contract_address_list
     *
     * @return the value of tickers.contract_address_list
     *
     * @mbg.generated
     */
    public String getContractAddressList() {
        return contractAddressList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.contract_address_list
     *
     * @param contractAddressList the value for tickers.contract_address_list
     *
     * @mbg.generated
     */
    public void setContractAddressList(String contractAddressList) {
        this.contractAddressList = contractAddressList == null ? null : contractAddressList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.marketcap
     *
     * @return the value of tickers.marketcap
     *
     * @mbg.generated
     */
    public Double getMarketcap() {
        return marketcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.marketcap
     *
     * @param marketcap the value for tickers.marketcap
     *
     * @mbg.generated
     */
    public void setMarketcap(Double marketcap) {
        this.marketcap = marketcap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.change24h
     *
     * @return the value of tickers.change24h
     *
     * @mbg.generated
     */
    public Double getChange24h() {
        return change24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.change24h
     *
     * @param change24h the value for tickers.change24h
     *
     * @mbg.generated
     */
    public void setChange24h(Double change24h) {
        this.change24h = change24h;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.change7d
     *
     * @return the value of tickers.change7d
     *
     * @mbg.generated
     */
    public Double getChange7d() {
        return change7d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.change7d
     *
     * @param change7d the value for tickers.change7d
     *
     * @mbg.generated
     */
    public void setChange7d(Double change7d) {
        this.change7d = change7d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tickers.rank
     *
     * @return the value of tickers.rank
     *
     * @mbg.generated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tickers.rank
     *
     * @param rank the value for tickers.rank
     *
     * @mbg.generated
     */
    public void setRank(String rank) {
        this.rank = rank == null ? null : rank.trim();
    }
}