package wang.raye.springboot.model;

import java.util.Date;

public class TradePointExclude {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.exchange
     *
     * @mbg.generated
     */
    private String exchange;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.symbol
     *
     * @mbg.generated
     */
    private String symbol;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.base
     *
     * @mbg.generated
     */
    private String base;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.period
     *
     * @mbg.generated
     */
    private String period;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.price
     *
     * @mbg.generated
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.kline_time
     *
     * @mbg.generated
     */
    private String klineTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_point_exclude.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.id
     *
     * @return the value of trade_point_exclude.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.id
     *
     * @param id the value for trade_point_exclude.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.exchange
     *
     * @return the value of trade_point_exclude.exchange
     *
     * @mbg.generated
     */
    public String getExchange() {
        return exchange;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.exchange
     *
     * @param exchange the value for trade_point_exclude.exchange
     *
     * @mbg.generated
     */
    public void setExchange(String exchange) {
        this.exchange = exchange == null ? null : exchange.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.symbol
     *
     * @return the value of trade_point_exclude.symbol
     *
     * @mbg.generated
     */
    public String getSymbol() {
        return symbol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.symbol
     *
     * @param symbol the value for trade_point_exclude.symbol
     *
     * @mbg.generated
     */
    public void setSymbol(String symbol) {
        this.symbol = symbol == null ? null : symbol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.base
     *
     * @return the value of trade_point_exclude.base
     *
     * @mbg.generated
     */
    public String getBase() {
        return base;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.base
     *
     * @param base the value for trade_point_exclude.base
     *
     * @mbg.generated
     */
    public void setBase(String base) {
        this.base = base == null ? null : base.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.period
     *
     * @return the value of trade_point_exclude.period
     *
     * @mbg.generated
     */
    public String getPeriod() {
        return period;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.period
     *
     * @param period the value for trade_point_exclude.period
     *
     * @mbg.generated
     */
    public void setPeriod(String period) {
        this.period = period == null ? null : period.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.price
     *
     * @return the value of trade_point_exclude.price
     *
     * @mbg.generated
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.price
     *
     * @param price the value for trade_point_exclude.price
     *
     * @mbg.generated
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.status
     *
     * @return the value of trade_point_exclude.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.status
     *
     * @param status the value for trade_point_exclude.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.kline_time
     *
     * @return the value of trade_point_exclude.kline_time
     *
     * @mbg.generated
     */
    public String getKlineTime() {
        return klineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.kline_time
     *
     * @param klineTime the value for trade_point_exclude.kline_time
     *
     * @mbg.generated
     */
    public void setKlineTime(String klineTime) {
        this.klineTime = klineTime == null ? null : klineTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_point_exclude.time
     *
     * @return the value of trade_point_exclude.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_point_exclude.time
     *
     * @param time the value for trade_point_exclude.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }
}